// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'IEMessage': string;
  'IEMessage-body': string;
  'IEMessage-button': string;
  'IEMessage-buttonPrimary': string;
  'IEMessage-buttonTertiary': string;
  'IEMessageWrapper': string;
  'close-btn': string;
  'closeBtn': string;
  'highlight': string;
  'ieMessage': string;
  'ieMessageBody': string;
  'ieMessageButton': string;
  'ieMessageButtonPrimary': string;
  'ieMessageButtonTertiary': string;
  'ieMessageWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
